spring.application.name=springai
server.port=8083
#api keyfor openAI
spring.ai.openai.api-key=${OPENAI_API_KEY}


spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=codellama:latest