spring.application.name=springai
server.port=8081
#api keyfor openAI
spring.ai.openai.api-key=${OPENAI_API_KEY}
  //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
